[program: llmops_uwsgi]
#command = uwsgi --ini /opt/opsany/uwsgi/llmops.ini
command = uvicorn llmops.asgi:application --host 0.0.0.0 --port 7000 --workers 4
directory = /opt/opsany/llmops
stdout_logfile = /opt/opsany/logs/llmops/uwsgi.log
redirect_stderr = true
autorestart = true
stopsignal = QUIT
stopasgroup=true
killasgroup=true
environment = BK_ENV="production",BK_LOG_DIR="/opt/opsany/logs/"
