# Paas域名地址(用来获取堡垒机主机数据)
PAAS_DOMAIN: DOMAIN_NAME
# 绑定IP
BIND_HOST: 0.0.0.0
# 绑定端口
SSHD_PORT: 8013
# 堡垒机秘钥用来解析密码
SECRET_KEY: BASTION_SECRET_KEY
# 测试环境 testing 生成环境 production
BASTION_ENV: production

# Redis相关配置
REDIS_HOST: FOOT_REDIS_HOST
REDIS_PORT: FOOT_REDIS_PORT
REDIS_DB: 8
REDIS_USERNAME: FOOT_REDIS_USERNAME
REDIS_PASSWORD: FOOT_REDIS_PASSWORD

# MySQL相关配置
MYSQL_HOST: FOOT_MYSQL_HOST
MYSQL_PORT: FOOT_MYSQL_PORT
MYSQL_USERNAME: bastion
MYSQL_PASSWORD: FOOT_MYSQL_PASSWORD
MYSQL_DB_NAME: bastion

# 日志级别
LOG_LEVEL: ERROR
# 调试模式
DEBUG: false

# 主机列表默认页数
PAGE_SIZE: 30
# 登录失败锁定次数
LOCK_LOGIN_FAILURE_COUNT: 5
# 锁定时间 单位小时
LOGIN_FAILURE_LOCK_HOUR: 24

# 连接超时时间
SSH_TIMEOUT: 3
# 心跳间隔时间
HEARTBEAT_INTERVAL: 20
# 最大连接数
MAX_CONNECTIONS: 500
# 语言
LANGUAGE_CODE: zh
SECURITY_MAX_IDLE_TIME: 60
ASSET_LIST_PAGE_SIZE: auto
REUSE_CONNECTION: true
FORCE_REMOVE_FOLDER: false
VERSION: 2.3.0

