apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsany-paas-websocket.fullname" . }}
  labels:
    {{- include "opsany-paas-websocket.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsany-paas-websocket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opsany-paas-websocket.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opsany-logs
              mountPath: /opt/opsany/logs
            - name: opsany-uploads
              mountPath: /opt/opsany/uploads
            - name: opsany-paas-websocket-config
              mountPath: /opt/opsany/websocket/config/prod.py
              subPath: prod.py
            - name: opsany-paas-websocket-init
              mountPath: /opt/opsany/websocket/config/__init__.py
              subPath: __init__.py
            - name: opsany-paas-websocket-supervisor
              mountPath: /etc/supervisord.d/websocket.ini
              subPath: websocket.ini
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          ports:
            - name: websocket
              containerPort: 8004
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: opsany-paas-websocket-config
          configMap:
            name: opsany-paas-websocket-config
            items:
            - key: settings_production.py.websocket
              path: prod.py
        - name: opsany-paas-websocket-init
          configMap:
            name: opsany-paas-websocket-init
            items:
            - key: settings_production.py.websocket.init
              path: __init__.py
        - name: opsany-paas-websocket-supervisor
          configMap:
            name: opsany-paas-websocket-supervisor
            items:
            - key: websocket.ini
              path: websocket.ini
        - name: opsany-logs
          persistentVolumeClaim:
            claimName: opsany-logs
        - name: opsany-uploads
          persistentVolumeClaim:
            claimName: opsany-uploads
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File

