# Generated by Django 4.2.16 on 2026-01-29 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bkaccount', '0010_alter_bkrole_code_alter_bkrole_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkTokenApiAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户信息')),
                ('token_type', models.CharField(default='login', max_length=128, verbose_name='Token类型')),
                ('auth_type', models.CharField(db_index=True, default='1', max_length=128, verbose_name='平台认证方式')),
                ('auth_platform', models.CharField(db_index=True, default='', max_length=255, null=True, verbose_name='授权平台')),
                ('apis', models.JSONField(default=list, null=True, verbose_name='相关内容')),
            ],
            options={
                'verbose_name': '登录票据API认证数据',
                'verbose_name_plural': '登录票据API认证数据',
                'db_table': 'login_bktoken_api_auth',
            },
        ),
        migrations.AddField(
            model_name='bktoken',
            name='auth_platform',
            field=models.JSONField(default=list, null=True, verbose_name='相关内容'),
        ),
        migrations.AddField(
            model_name='bktoken',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bktoken',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='bktoken',
            name='token_type',
            field=models.CharField(default='login', max_length=128, verbose_name='Token类型'),
        ),
        migrations.AddField(
            model_name='bktoken',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bktoken',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='用户信息'),
        ),
        migrations.AddField(
            model_name='bktoken',
            name='call_count',
            field=models.IntegerField(default=0, verbose_name='调用次数'),
        ),
        migrations.AddIndex(
            model_name='bktoken',
            index=models.Index(fields=['username'], name='bktoken_username_idx'),
        ),
        migrations.AddIndex(
            model_name='bktoken',
            index=models.Index(fields=['token_type'], name='bktoken_token_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bktoken',
            index=models.Index(fields=['expire_time'], name='bktoken_expire_time_idx'),
        ),
        migrations.AddField(
            model_name='bktokenapiauthmodel',
            name='bk_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkaccount.bktoken'),
        ),
        migrations.AddIndex(
            model_name='bktokenapiauthmodel',
            index=models.Index(fields=['username'], name='bktokenapi_username_idx'),
        ),
        migrations.AddIndex(
            model_name='bktokenapiauthmodel',
            index=models.Index(fields=['token_type'], name='bktokenapi_token_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bktokenapiauthmodel',
            index=models.Index(fields=['auth_type'], name='bktokenapi_auth_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bktokenapiauthmodel',
            index=models.Index(fields=['auth_platform'], name='bktokenapi_auth_platform_idx'),
        ),
    ]
