apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsany-paas-login.fullname" . }}
  labels:
    {{- include "opsany-paas-login.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsany-paas-login.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opsany-paas-login.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: opsany-paas-login-config
              mountPath: /opt/opsany/paas/login/conf/settings_production.py
              subPath: settings_production.py
            - name: opsany-paas-login-supervisor
              mountPath: /etc/supervisord.d/login.ini
              subPath: login.ini
            - name: opsany-logs
              mountPath: /opt/opsany/logs
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: paas-login
              containerPort: 8003
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: opsany-paas-login-config
          secret:
            secretName: opsany-paas-login-config
            items:
            - key: settings_production.py.login
              path: settings_production.py
        - name: opsany-paas-login-supervisor
          secret:
            secretName: opsany-paas-login-supervisor
            items:
            - key: login.ini
              path: login.ini
        - name: opsany-logs
          persistentVolumeClaim:
            claimName: opsany-logs
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
